[project]
name = "c-fit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.52.0",
    "dotenv>=0.9.9",
    "json-repair>=0.50.0",
    "langchain>=0.3.27",
    "langchain-google-genai>=2.1.10",
    "langgraph>=0.6.6",
    "trafilatura>=2.0.0",
]
